import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
    en: {
        nav: {
            home: 'Home',
            products: 'Products',
            about: 'About',
            team: 'Team',
            contact: 'Contact',
        },
        slider: {
            slide1: {
                subtitle: 'Redefining Quality – Dairy Products from the Heart of Gir.',
                title: 'Raw Milk\'s Natural Resources from the Gir Rain Forest Area.',
                btn_primary: 'Explore Our Range',
                btn_secondary: 'Learn About Us'
            },
            slide2: {
                subtitle: 'Empowering the Maldhari Community.',
                title: 'Sourcing from 58 villages with 60 milk collection centers.',
                btn_primary: 'Shop Pure Products',
                btn_secondary: 'Discover Our Story'
            },
            slide3: {
                subtitle: "Blending Tradition with Modern Scale",
                title: 'Presently we have a 30,000 sq. feet factory layout with well-maintained equipment, backed by over 20 years of experience.',
                btn_primary: 'View Product Range',
                btn_secondary: 'Contact Our Team'
            }
        },
        home: {
            welcome: 'Welcome to our dairy farm',
            hero_title: 'PRASAD DAIRY',
            our_products: 'Our Products',
            about_us: 'About Us',
            know_about: 'Our Heritage in Gir',
            know_about_sub: 'Purity Since 1995',
            know_about_desc: 'Founded in the heart of Talala-Gir, Prasad Dairy has more than 20 years of experience in crafting premium dairy products. We started our journey in a humble 10x10 shed and have since grown into a sophisticated 30,000 sq. feet factory layout equipped with modern, well-maintained equipment. Our heritage is rooted in the natural resources of the Gir Rain Forest Area, where we source raw milk of the highest quality. Our journey began by gathering fresh milk from neighboring villages, and today, our extensive collection network covers 58 villages with 60 dedicated milk collection centers throughout the Gir Forest. We are committed to empowering the Maldhari community and providing our customers with pure, fresh, and organic dairy products that carry the essence of our land.',
            award: 'YOUNG FARMER EXCELLENCE AWARD 2022',
            service_details: 'Explore Our Services',
            read_more: 'Learn More About Our Journey',
            services: 'Our Specialized Services',
            what_provide: 'PREMIUM DAIRY SOLUTIONS',
            fresh_milk: 'Fresh Raw Milk & Probiotic Curd',
            dairy_products: 'Traditional Dairy Delicacies',
            organic_product: '100% Organic Products',
            stats_projects: 'Milk Collection Centers',
            stats_mates: 'Maldhari Families Empowered',
            stats_capture: 'Liters Collected Daily',
            stats_customers: 'Satisfied Customers',
            stats_satisfaction: 'Quality Assurance Rating',
            testimonials_title: 'Our Testimonials',
            testimonials_heading: 'WHAT PEOPLE SAY',
            testimonials_quote: 'Farmers tend to be predominantly enterprising individuals, which means that they are usually quite natural leaders who thrive at influencing and persuading others.',
            featured_title: 'Featured',
            featured_heading: 'FEATURED PRODUCTS',
            more_products: 'More Products',
            farm_house: 'The Farm House',
            organic_100: '100%',
            farm_fresh: '100% Pure',
            made_love: 'Made with Love',
            premium_quality: 'Premium Quality',
            team_title: 'Our Team',
            team_heading: 'EXPERT FARMER',
            why_choose: 'Why Choose Us',
            why_choose_heading: 'BEST DAIRY FARM',
        },
        products: {
            shop_now: 'Shop Now',
            title: 'OUR PRODUCTS',
            search_placeholder: 'Search products...',
            view_details: 'View Details',
            milk_solids: 'Milk Solids',
            desserts: 'Desserts',
            yogurt: 'Yogurt',
            cheese_cat: 'Cheese',
            spreads: 'Spreads',
            beverages: 'Beverages',
            khoa: 'Mawa / Khoya',
            khoa_desc: 'Traditional pure milk solids available in Regular, Danedar, and Bengali varieties. Offered in Classic, Super, and A-one quality grades. Bulk 10kg packaging with customization available.',
            plain_mawo: 'Plain Mawo',
            plain_mawo_desc: 'Pure and fresh Plain Mawo from the famous farms of Gir. Ideal for authentic traditional cooking and sweets. Available in 1kg and 10kg packaging.',
            shrikhand: 'Shrikhand',
            shrikhand_desc: 'Premium creamy Shrikhand available in a wide range of exotic flavors including Plain, Green Fruit, Shahi Rajbhog, Butterscotch, Kesar Pista, Afghani Mewa, Rajwadi Dryfruit, Mawa Badam, Pancharatana Delight, American Nuts, and Chappan Bhog. Available in sizes from 500g to 20kg with customization options.',
            chakka: 'Chakka / Maska',
            chakka_desc: 'Thick, strained yogurt base used for making Shrikhand and other traditional desserts.',
            maska_full_cream: 'Full Cream Maska',
            maska_full_cream_desc: 'Rich and creamy Maska made from high-quality full cream milk, ideal for traditional sweets.',
            maska_low_fat: 'Low Fat Maska',
            maska_low_fat_desc: 'A lighter version of our traditional Maska, providing the same great texture with less fat.',
            paneer: 'Fresh Malai Paneer',
            paneer_desc: 'Extra soft and creamy Malai Paneer, rich in protein and crafted for the perfect texture in every dish. Available in 200g, 1kg, and 5kg packs.',
            butter: 'Pure Cooking Butter',
            butter_desc: 'Traditional desi cooking butter, freshly churned for authentic taste and aroma. Available in 1kg to 20kg bulk packaging with customization available for specific requirements.',
            curd: 'Fresh Curd (Dahi)',
            curd_desc: 'Thick, creamy, and naturally fermented yogurt, rich in probiotics for gut health.',
            ghee: 'Desi Ghee',
            ghee_desc: 'Traditionally crafted clarified butter with a rich aroma and granular texture.',
            a2_ghee: 'A2 Cow Ghee',
            a2_ghee_desc: 'Premium ghee made from Gir cow milk using the traditional Bilona method.',
            chaas: 'Buttermilk (Chaas)',
            chaas_desc: 'Refreshing and light traditional buttermilk, a perfect natural coolant.',
            masala_chhas: 'Masala Chhas',
            masala_chhas_desc: 'Spiced buttermilk with a blend of traditional Indian herbs and spices, refreshing and digestive.',
            sweets: 'Traditional Sweets',
            sweets_desc: 'An exquisite collection of artisanal Mawa, Dry Fruit, and Bengali sweets, handcrafted with pure Prasad Dairy ingredients and traditional recipes.',
            lassi: 'Sweet Lassi',
            lassi_desc: 'Creamy and refreshing yogurt-based drink, perfectly blended for a smooth texture.',
            sweets_general: 'Milk Sweets',
            sweets_general_desc: 'A delightful assortment of traditional sweets made from our milk and mawa.',
            thabdi: 'Traditional Thabdi',
            thabdi_desc: 'Authentic Saurashtra style Thabdi, slow-cooked to perfection. Available in Thabdi Dano and Special Thabdi varieties. Bulk 10kg packaging available.',
            basundi: 'Premium Basundi',
            basundi_desc: 'Rich, thickened sweetened milk dessert flavored with cardamom and saffron, crafted for celebrations. Available in bulk 20kg packaging.',
            packaging: 'Available Packaging',
        },
        product_detail: {
            home: 'Home',
            products: 'Products',
            reviews: 'Reviews',
            add_to_cart: 'Add to Cart',
            sku: 'SKU',
            category: 'Category',
            tags: 'Tags',
            tags_value: 'Organic, Fresh, Dairy',
            desc_suffix: 'Made from 100% organic milk from our happy buffalo. Rich in nutrients and authentic taste.',
            packaging: 'Packaging',
            storage: 'Storage',
            origin: 'Origin',
            whatsapp_chat: 'Chat on WhatsApp',
            bulk_order_title: 'Bulk Order & Customization',
            bulk_order_desc: 'Customization available as per request.',
            bulk_order_inquiry: 'Inquire for Bulk Order',
        },
        about: {
            who_we_are: 'Who We Are',
            title: 'ABOUT US',
            introductions: 'Our History',
            heading: 'Our History',
            description1: 'Founded in Gir\'s capital, we have more than 20 years of experience.Raw Milk\'s Natural Resources because of the Gir Rain Forest Area.',
            description2: 'We started out in a 10x10 shed. Presently we have a 30,000 sq. feet factory layout with well-maintained equipment.',
            description3: 'Our journey began by gathering milk from neighbouring villages.\n' +
                'Currently our collection includes the entire Gir Forest Area and neighbouring Talukas contain 58 villages with 60 milk collection centers. Last year, we achieved a daily milk collection capacity of over 20,000 liters, and we are still growing.',
            years_exp: 'Years of Experience in Dairy Industry',
            natural_products: '100% Natural Products',
            modern_tech: 'Modern Technology',
            certified_organic: 'Certified Organic',
            expert_farmers: 'Expert Farmers',
            discover_more: 'Discover More',
            v: {
                title: 'Our Vision',
                desc1: 'Our vision is to empower the Maldhari community by fostering sustainable practices and building a collaborative ecosystem, with the ambitious goal of collecting 1,82,50,000 liters of milk per annum.',
                desc2: 'Exploring high values for Quality and Standards with no compromise in Quality and Purity.'
            },
            cv:{
                title: 'Core Values',
                quality: 'Quality',
                quality_desc: 'Ensuring high standards in the production and processing of dairy products.',
                integrity: 'Integrity',
                integrity_desc: 'Conducting business with honesty and transparency, from sourcing to distribution.',
                innovation:'Innovation',
                innovation_desc: 'Embracing new technologies and methods to improve efficiency and product quality.',
                customer_focus:'Customer Focus',
                customer_focus_desc: 'Prioritizing customer satisfaction through consistent quality and service.',
                community_engagement:'Community Engagement',
                community_engagement_desc: 'Contributing positively to local communities, supporting farmers, and participating in community initiatives.',
                continuous_improvement:'Continuous Improvement',
                continuous_improvement_desc: 'Striving for ongoing improvement in processes, products, and sustain ability practices.'


            }
        },

        team: {
            meet_farmers: 'Meet the Farmers',
            title: 'OUR TEAM',
            founder: 'Founder',
            head_idea: 'Head of Idea',
            ceo: 'CEO',
            farmer: 'Farmer',
            designer: 'Designer',
            marketer: 'Marketer',
        },
        contact: {
            get_touch: 'Get in Touch',
            title: 'CONTACT US',
            phone: 'Phone Number',
            email: 'Email Address',
            location: 'Location',
            opening_hours: 'Opening Hours',
            send_message: 'Send Message',
            heading: 'WE LOVE TO HEAR FROM YOU',
            your_name: 'Your Name',
            your_email: 'Your Email',
            subject: 'Subject',
            message: 'Message',
            send_btn: 'Send Message',
            sent_success: 'Message Sent!',
            sent_desc: "We'll get back to you as soon as possible.",
        },
        footer: {
            about_us: 'About Us',
            about_desc: 'Prasad Dairy Products is dedicated to bringing the purest, freshest dairy from our farm directly to your table. Tradition meets quality in every drop.',
            products: 'Products',
            business_hours: 'Business Hours',
            quick_links: 'Quick Links',
            subscribe: 'Subscribe Us',
            subscribe_desc: 'Subscribe us & receive our office & update in your inbox directly',
            email_placeholder: 'Email address',
            subscribe_btn: 'Subscribe',
            rights: '2025 Prasad Dairy Products. All rights reserved.',
            emergency: 'Contact Number',
            mon_fri: 'Mon - Sat',
            sat: 'Sunday',
            careers: 'Careers',
            faq: 'FAQ',
            contact: 'Contact Us',
            privacy: 'Privacy Policy',
            terms: 'Terms of Service',
            shipping: 'Shipping Info',
            returns: 'Returns & Refunds',
        },
        seo: {
            home_title: 'Prasad Dairy Products | Pure Desi Ghee & Fresh Dairy from Gir',
            home_desc: 'Experience the purity of Prasad Dairy. We offer authentic Desi Ghee, Shrikhand, Paneer, and fresh milk products sourced from 58 villages in the Gir Forest area.',
            home_keywords: 'Prasad Dairy, Desi Ghee Gir, Fresh Milk Gujarat, Shrikhand Talala, Pure Dairy Products India, Organic Ghee, Gir Cow Ghee',
            products_title: 'Our Premium Dairy Products | Prasad Dairy',
            products_desc: 'Browse our range of pure dairy products: Ghee, Mawa, Shrikhand, Basundi, and Malai Paneer. Crafted with generational expertise and uncompromising purity.',
            products_keywords: 'Dairy Products List, Buy Ghee Online, Shrikhand Flavors, Pure Mawa Khoya, Fresh Paneer Gujarat',
            about_title: 'Our Legacy & Mission | About Prasad Dairy',
            about_desc: 'Founded in Gir, Prasad Dairy has over 20 years of experience. We empower the Maldhari community and source fresh milk from the Gir Rain Forest area.',
            about_keywords: 'Prasad Dairy History, Gir Dairy Farm, Maldhari Community Support, Sustainable Dairy Farming',
            team_title: 'Meet Our Dedicated Team | Prasad Dairy',
            team_desc: 'Meet the passionate farmers and experts behind Prasad Dairy. Our team ensures the highest quality standards from farm to table.',
            contact_title: 'Contact Us | Prasad Dairy Products',
            contact_desc: 'Have questions? Contact Prasad Dairy for bulk orders or inquiries about our fresh dairy products. We love to hear from our customers.',
        }
    },
    gu: {
        nav: {
            home: 'મુખ્ય પૃષ્ઠ',
            products: 'ઉત્પાદનો',
            about: 'અમારા વિશે',
            team: 'ટીમ',
            contact: 'સંપર્ક',
        },
        slider: {
            slide1: {
                subtitle: 'અમારા ડેરી ફાર્મ પર આપનું સ્વાગત છે',
                title: 'પ્રસાદ ડેરી',
                btn_primary: 'અમારા ઉત્પાદનો',
                btn_secondary: 'અમારા વિશે'
            },
            slide2: {
                subtitle: 'શુદ્ધ અને સ્વસ્થ',
                title: 'દરરોજ તાજું દૂધ',
                btn_primary: 'હમણાં ખરીદો',
                btn_secondary: 'વધુ શીખો'
            },
            slide3: {
                subtitle: 'કુદરતનું શ્રેષ્ઠ',
                title: '100% ઓર્ગેનિક ઉત્પાદનો',
                btn_primary: 'શ્રેણી જુઓ',
                btn_secondary: 'અમારો સંપર્ક કરો'
            }
        },
        home: {
            welcome: 'અમારા ડેરી ફાર્મ પર આપનું સ્વાગત છે',
            hero_title: 'પ્રસાદ ડેરી',
            our_products: 'અમારા ઉત્પાદનો',
            about_us: 'અમારા વિશે',
            know_about: 'અમારા ફાર્મ અને ઇતિહાસ વિશે જાણો',
            know_about_sub: 'અમારા વિશે',
            know_about_desc: 'અમે વિશ્વાસ અને પ્રામાણિકતા સાથે 30 વર્ષથી વધુ સમયથી આ ઉદ્યોામાં કાર્યરત છીએ. જો આપણે વૈશ્વિક પોષણ સુધારવા માટે અમારું લક્ષ્ય પ્રાપ્ત કરવું હોય તો બધાએ સાથે મળીને કામ કરવું પડશે.',
            award: 'યંગ ફાર્મ એવોર્ડ 2022',
            service_details: 'સેવા વિગતો',
            read_more: 'વધુ વાંચો',
            services: 'સેવાઓ',
            what_provide: 'અમે શું પ્રદાન કરીએ છીએ',
            fresh_milk: 'તાજું દૂધ અને દહીં',
            dairy_products: 'ડેરી ઉત્પાદનો',
            organic_product: 'ઓર્ગેનિક ઉત્પાદન',
            stats_projects: 'પ્રોજેક્ટ્સ પૂર્ણ',
            stats_mates: 'નિષ્ણાત સાથીઓ',
            stats_capture: 'વિશ્વવ્યાપી કેપ્ચર',
            stats_customers: 'ખુશ ગ્રાહકો',
            stats_satisfaction: 'સંતોષ',
            testimonials_title: 'અમારા પ્રશંસાપત્રો',
            testimonials_heading: 'લોકો શું કહે છે',
            testimonials_quote: 'ખેડૂતો મુખ્યત્વે સાહસિક વ્યક્તિઓ હોય છે, જેનો અર્થ એ છે કે તેઓ સામાન્ય રીતે કુદરતી નેતાઓ હોય છે જે અન્યને પ્રભાવિત કરવામાં અને સમજાવવામાં સફળ થાય છે.',
            featured_title: 'વિશિષ્ટ',
            featured_heading: 'વિશિષ્ટ ઉત્પાદનો',
            more_products: 'વધુ ઉત્પાદનો',
            farm_house: 'ફાર્મ હાઉસ',
            organic_100: '100% ઓર્ગેનિક',
            farm_fresh: 'ફાર્મ તાજું',
            made_love: 'પ્રેમથી બનાવેલ',
            premium_quality: 'પ્રીમિયમ ગુણવત્તા',
            team_title: 'અમારી ટીમ',
            team_heading: 'નિષ્ણાત ખેડૂત',
            news_title: 'સમાચાર ફીડ્સ',
            news_heading: 'બ્લોગ અને આંતરદૃષ્ટિ',
            more_news: 'વધુ સમાચાર',
        },
        products: {
            shop_now: 'હમણાં ખરીદો',
            title: 'અમારા ઉત્પાદનો',
            search_placeholder: 'ઉત્પાદનો શોધો...',
            view_details: 'વિગતો જુઓ',
            milk_solids: 'દૂધના ઘન પદાર્થો',
            desserts: 'મીઠાઈઓ',
            yogurt: 'દહીં',
            cheese_cat: 'ચીઝ',
            spreads: 'સ્પ્રેડ્સ',
            beverages: 'પીણાં',
            khoa: 'માવો / ખોયા',
            khoa_desc: 'પરંપરાગત શુદ્ધ દૂધના ઘન પદાર્થો, અધિકૃત ભારતીય મીઠાઈઓ માટે ઉત્તમ આધાર.',
            plain_mawo: 'પ્લેઈન માવો',
            plain_mawo_desc: 'ગીરના પ્રખ્યાત ફાર્મમાંથી શુદ્ધ અને તાજો પ્લેઈન માવો. અધિકૃત પરંપરાગત રસોઈ અને મીઠાઈઓ માટે આદર્શ. 1 કિલો અને 10 કિલો પેકેજિંગમાં ઉપલબ્ધ છે.',
            shrikhand: 'શ્રીખંડ',
            shrikhand_desc: 'કેસર અને ઈલાયચીથી સ્વાદિષ્ટ બનાવેલ ગાળેલા દહીંની ક્રીમી અને મીઠી મીઠાઈ.',
            chakka: 'ચક્કા / મસ્કા',
            chakka_desc: 'શ્રીખંડ અને અન્ય પરંપરાગત મીઠાઈઓ બનાવવા માટે વપરાતો ઘટ્ટ ગાળેલો દહીંનો આધાર.',
            maska_full_cream: 'ફુલ ક્રીમ મસ્કા',
            maska_full_cream_desc: 'ઉચ્ચ ગુણવત્તાવાળા ફૂલ ક્રીમ દૂધમાંથી બનાવેલ સમૃદ્ધ અને ક્રીમી મસ્કા, પરંપરાગત મીઠાઈઓ માટે આદર્શ.',
            maska_low_fat: 'લો ફેટ મસ્કા',
            maska_low_fat_desc: 'અમારા પરંપરાગત મસ્કાનું હળવું સંસ્કરણ, ઓછી ચરબી સાથે સમાન ઉત્તમ ટેક્સચર પ્રદાન કરે છે.',
            paneer: 'તાજું પનીર',
            paneer_desc: 'શુદ્ધ દૂધમાંથી બનાવેલ નરમ અને ક્રીમી પનીર, પ્રોટીન અને સ્વાદથી ભરપૂર.',
            butter: 'સફેદ માખણ (લોણી)',
            butter_desc: 'તાજું વલોવેલું પરંપરાગત સફેદ માખણ, શુદ્ધ અને કુદરતી સ્વાદથી ભરપૂર.',
            curd: 'તાજું દહીં',
            curd_desc: 'ઘટ્ટ, ક્રીમી અને કુદરતી રીતે આથો લાવેલ દહીં, પાચન માટે પ્રોબાયોટિક્સથી સમૃદ્ધ.',
            ghee: 'દેશી ઘી',
            ghee_desc: 'પરંપરાગત રીતે તૈયાર કરેલ સ્પષ્ટ માખણ, જે તેની સુગંધ અને દાણાદાર રચના માટે જાણીતું છે.',
            a2_ghee: 'A2 ગાયનું ઘી',
            a2_ghee_desc: 'પરંપરાગત બિલોના પદ્ધતિનો ઉપયોગ કરીને ગીર ગાયના દૂધમાંથી બનાવેલ પ્રીમિયમ ઘી.',
            chaas: 'છાસ',
            chaas_desc: 'તાજગી આપનારી અને હલકી પરંપરાગત છાસ, દરેક ભોજન માટે એક ઉત્તમ કુદરતી ઠંડક.',
            masala_chhas: 'મસાલા છાસ',
            masala_chhas_desc: 'પરંપરાગત ભારતીય જડીબુટ્ટીઓ અને મસાલાઓના મિશ્રણ સાથેની મસાલેદાર છાસ, તાજગી આપનારી અને પાચક.',
            sweets: 'પરંપરાગત મીઠાઈઓ',
            sweets_desc: 'પ્રસાદ ડેરીના શુદ્ધ ઘટકોમાંથી બનેલી માવા, ડ્રાય ફ્રૂટ અને બંગાળી મીઠાઈઓનો ઉત્કૃષ્ટ સંગ્રહ.',
            lassi: 'સ્વીટ લસ્સી',
            lassi_desc: 'ક્રીમી અને તાજગી આપનારું દહીં આધારિત પીણું, જે સ્મૂધ ટેક્સચર માટે યોગ્ય રીતે બ્લેન્ડ કરેલું છે.',
            sweets_general: 'દૂધની મીઠાઈઓ',
            sweets_general_desc: 'અમારા શુદ્ધ દૂધ અને માવામાંથી બનાવેલી પરંપરાગત મીઠાઈઓનો આનંદદાયક સંગ્રહ.',
            packaging: 'ઉપલબ્ધ પેકેજિંગ',
        },
        product_detail: {
            home: 'મુખ્ય પૃષ્ઠ',
            products: 'ઉત્પાદનો',
            reviews: 'સમીક્ષાઓ',
            add_to_cart: 'કાર્ટમાં ઉમેરો',
            sku: 'એસકેયુ',
            category: 'શ્રેણી',
            tags: 'ટૅગ્સ',
            tags_value: 'ઓર્ગેનિક, તાજું, ડેરી',
            desc_suffix: 'અમારી ખુશ ગાયોના 100% ઓર્ગેનિક દૂધમાંથી બનાવેલ. પોષક તત્વો અને અધિકૃત સ્વાદથી સમૃદ્ધ.',
            packaging: 'પેકેજિંગ',
            storage: 'સંગ્રહ',
            origin: 'ઉત્પત્તિ',
            whatsapp_chat: 'વોટ્સએપ પર ચેટ કરો',
            bulk_order_title: 'બલ્ક ઓર્ડર અને કસ્ટમાઇઝેશન',
            bulk_order_desc: 'વિનંતી મુજબ કસ્ટમાઇઝેશન ઉપલબ્ધ છે. અમે મોટા પ્રસંગો, લગ્નો, હોટલ અને ચોક્કસ પેકેજિંગ/બ્રાન્ડિંગ વિકલ્પો માટે ઓર્ડર સ્વીકારીએ છીએ.',
            bulk_order_inquiry: 'બલ્ક ઓર્ડર માટે પૂછપરછ કરો',
        },
        about: {
            who_we_are: 'અમે કોણ છીએ',
            title: 'અમારા વિશે',
            introductions: 'અમારો પરિચય',
            heading: 'અમે શ્રેષ્ઠ ડેરી ફાર્મ છીએ',
            description: 'અમે કુદરતની શક્તિમાં માનીએ છીએ. અમારી ગાયો લીલા ઘાસના મેદાનોમાં મુક્તપણે ચરે છે, જે પોષક તત્વો અને સ્વાદથી ભરપૂર ઉચ્ચ ગુણવત્તાવાળું દૂધ સુનિશ્ચિત કરે છે.',
            years_exp: 'ડેરી ઉદ્યોગમાં વર્ષોનો અનુભવ',
            natural_products: '100% કુદરતી ઉત્પાદનો',
            modern_tech: 'આધુનિક ટેકનોલોજી',
            certified_organic: 'પ્રમાણિત ઓર્ગેનિક',
            expert_farmers: 'નિષ્ણાત ખેડૂતો',
            discover_more: 'વધુ શોધો',
        },
        team: {
            meet_farmers: 'ખેડૂતોને મળો',
            title: 'અમારી ટીમ',
            founder: 'સ્થાપક',
            head_idea: 'હેડ ઓફ આઈડિયા',
            ceo: 'સીઈઓ',
            farmer: 'ખેડૂત',
            designer: 'ડિઝાઈનર',
            marketer: 'માર્કેટર',
        },
        contact: {
            get_touch: 'સંપર્કમાં રહો',
            title: 'અમારો સંપર્ક કરો',
            phone: 'ફોન નંબર',
            email: 'ઇમેઇલ સરનામું',
            location: 'સ્થાન',
            opening_hours: 'ખુલવાનો સમય',
            send_message: 'સંદેશ મોકલો',
            heading: 'અમને તમારી પાસેથી સાંભળવું ગમશે',
            your_name: 'તમારું નામ',
            your_email: 'તમારું ઇમેઇલ',
            subject: 'વિષય',
            message: 'સંદેશ',
            send_btn: 'સંદેશ મોકલો',
            sent_success: 'સંદેશ મોકલ્યો!',
            sent_desc: 'અમે જલ્દીથી તમારો સંપર્ક કરીશું.',
        },
        footer: {
            about_us: 'અમારા વિશે',
            about_desc: 'પ્રસાદ ડેરી પ્રોડક્ટ્સ અમારા ફાર્મથી સીધા તમારા ટેબલ પર શુદ્ધ, તાજું દૂધ લાવવા માટે સમર્પિત છે. દરેક ટીપામાં પરંપરા ગુણવત્તાને મળે છે.',
            products: 'ઉત્પાદનો',
            business_hours: 'વ્યવસાયનો સમય',
            subscribe: 'અમને સબ્સ્ક્રાઇબ કરો',
            subscribe_desc: 'અમને સબ્સ્ક્રાઇબ કરો અને સીધા તમારા ઇનબોક્સમાં અમારા અપડેટ્સ મેળવો',
            email_placeholder: 'ઇમેઇલ સરનામું',
            subscribe_btn: 'સબ્સ્ક્રાઇબ',
            rights: '2025 પ્રસાદ ડેરી પ્રોડક્ટ્સ. સર્વાધિકાર સુરક્ષિત.',
            emergency: 'ઇમરજન્સી સેવા',
            mon_fri: 'સોમ - શુક્ર',
            sat: 'શનિવાર',
            careers: 'કારકિર્દી',
            faq: 'પ્રશ્નો',
            privacy: 'ગોપનીયતા નીતિ',
            terms: 'સેવાની શરતો',
            shipping: 'શિપિંગ માહિતી',
            returns: 'રિટર્ન અને રિફંડ',
        },
        seo: {
            home_title: 'પ્રસાદ ડેરી પ્રોડક્ટ્સ | શુદ્ધ દેશી ઘી અને ગીરનું તાજું દૂધ',
            home_desc: 'પ્રસાદ ડેરીની શુદ્ધતાનો અનુભવ કરો. અમે ગીર જંગલ વિસ્તારના 58 ગામોમાંથી મેળવેલા અધિકૃત દેશી ઘી, શ્રીખંડ, પનીર અને તાજા દૂધની બનાવટો પ્રદાન કરીએ છીએ.',
            home_keywords: 'પ્રસાદ ડેરી, દેશી ઘી ગીર, તાજું દૂધ ગુજરાત, શ્રીખંડ તાલાલા, શુદ્ધ ડેરી ઉત્પાદનો ભારત, ઓર્ગેનિક ઘી, ગીર ગાયનું ઘી',
            products_title: 'અમારા પ્રીમિયમ ડેરી ઉત્પાદનો | પ્રસાદ ડેરી',
            products_desc: 'અમારા શુદ્ધ ડેરી ઉત્પાદનોની શ્રેણી જુઓ: ઘી, માવો, શ્રીખંડ, બાસુંદી અને મલાઈ પનીર. પેઢીઓના અનુભવ અને અતૂટ શુદ્ધતા સાથે તૈયાર કરેલ.',
            products_keywords: 'ડેરી ઉત્પાદનોની સૂચિ, ઓનલાઇન ઘી ખરીદો, શ્રીખંડના ફ્લેવર્સ, શુદ્ધ માવો ખોયા, તાજું પનીર ગુજરાત',
            about_title: 'અમારો વારસો અને મિશન | પ્રસાદ ડેરી વિશે',
            about_desc: 'ગીરમાં સ્થપાયેલ, પ્રસાદ ડેરીને 20 વર્ષથી વધુનો અનુભવ છે. અમે માલધારી સમુદાયને સશક્ત કરીએ છીએ અને ગીર રેઈન ફોરેસ્ટ વિસ્તારમાંથી તાજું દૂધ મેળવીએ છીએ.',
            about_keywords: 'પ્રસાદ ડેરીનો ઇતિહાસ, ગીર ડેરી ફાર્મ, માલધારી સમુદાય સપોર્ટ, ટકાઉ ડેરી ખેતી',
            team_title: 'અમારી સમર્પિત ટીમને મળો | પ્રસાદ ડેરી',
            team_desc: 'પ્રસાદ ડેરી પાછળના ઉત્સાહી ખેડૂતો અને નિષ્ણાતોને મળો. અમારી ટીમ ફાર્મથી ટેબલ સુધી ઉચ્ચ ગુણવત્તાના ધોરણોની ખાતરી કરે છે.',
            contact_title: 'અમારો સંપર્ક કરો | પ્રસાદ ડેરી પ્રોડક્ટ્સ',
            contact_desc: 'કોઈ પ્રશ્નો છે? જથ્થાબંધ ઓર્ડર અથવા અમારા તાજા ડેરી ઉત્પાદનો વિશે પૂછપરછ માટે પ્રસાદ ડેરીનો સંપર્ક કરો.',
        }
    },
    hi: {
        nav: {
            home: 'मुख्य पृष्ठ',
            products: 'उत्पाद',
            about: 'हमारे बारे में',
            team: 'टीम',
            contact: 'संपर्क',
        },
        slider: {
            slide1: {
                subtitle: 'हमारे डेयरी फार्म में आपका स्वागत है',
                title: 'प्रसाद डेयरी',
                btn_primary: 'हमारे उत्पाद',
                btn_secondary: 'हमारे बारे में'
            },
            slide2: {
                subtitle: 'शुद्ध और स्वस्थ',
                title: 'हर दिन ताजा दूध',
                btn_primary: 'अभी खरीदें',
                btn_secondary: 'और जानें'
            },
            slide3: {
                subtitle: 'प्रकृति का सर्वश्रेष्ठ',
                title: '100% जैविक उत्पाद',
                btn_primary: 'रेंज देखें',
                btn_secondary: 'संपर्क करें'
            }
        },
        home: {
            welcome: 'हमारे डेयरी फार्म में आपका स्वागत है',
            hero_title: 'प्रसाद डेयरी',
            our_products: 'हमारे उत्पाद',
            about_us: 'हमारे बारे में',
            know_about: 'हमारे फार्म और इतिहास के बारे में जानें',
            know_about_sub: 'हमारे बारे में',
            know_about_desc: 'हम 30 से अधिक वर्षों से विश्वास और ईमानदारी के साथ इस उद्योग में काम कर रहे हैं। यदि हमें वैश्विक पोषण में सुधार के अपने लक्ष्य को प्राप्त करना है तो सभी को मिलकर काम करना होगा।',
            award: 'यंग फार्म अवार्ड 2022',
            service_details: 'सेवा विवरण',
            read_more: 'और पढ़ें',
            services: 'सेवाएं',
            what_provide: 'हम क्या प्रदान करते हैं',
            fresh_milk: 'ताजा दूध और दही',
            dairy_products: 'डेयरी उत्पाद',
            organic_product: 'जैविक उत्पाद',
            stats_projects: 'परियोजनाएं पूर्ण',
            stats_mates: 'विशेषज्ञ साथी',
            stats_capture: 'विश्वव्यापी पहुंच',
            stats_customers: 'खुश ग्राहक',
            stats_satisfaction: 'संतुष्टि',
            testimonials_title: 'हमारे प्रशंसापत्र',
            testimonials_heading: 'लोग क्या कहते हैं',
            testimonials_quote: 'किसान मुख्य रूप से उद्यमी व्यक्ति होते हैं, जिसका अर्थ है कि वे आमतौर पर काफी स्वाभाविक नेता होते हैं जो दूसरों को प्रभावित करने और राजी करने में सफल होते हैं।',
            featured_title: 'विशेष',
            featured_heading: 'विशेष उत्पाद',
            more_products: 'अधिक उत्पाद',
            farm_house: 'फार्म हाउस',
            organic_100: '100% जैविक',
            farm_fresh: 'खेत का ताजा',
            made_love: 'प्यार से बनाया गया',
            premium_quality: 'प्रीमियम गुणवत्ता',
            team_title: 'हमारी टीम',
            team_heading: 'विशेषज्ञ किसान',
            news_title: 'समाचार फ़ीड',
            news_heading: 'ब्लॉग और अंतर्दृष्टि',
            more_news: 'अधिक समाचार',
        },
        products: {
            shop_now: 'अभी खरीदारी करें',
            title: 'हमारे उत्पाद',
            search_placeholder: 'उत्पाद खोजें...',
            view_details: 'विवरण देखें',
            milk_solids: 'दूध के ठोस पदार्थ',
            desserts: 'मिठाईयाँ',
            yogurt: 'दही',
            cheese_cat: ' पनीर',
            spreads: 'स्प्रेड्स',
            beverages: 'पेय पदार्थ',
            khoa: 'खोया / मावा',
            khoa_desc: 'पारंपरिक शुद्ध दूध के ठोस पदार्थ, प्रामाणिक भारतीय मिठाइयों के लिए उत्तम आधार।',
            plain_mawo: 'प्लेन मावा',
            plain_mawo_desc: 'गीर के प्रसिद्ध खेतों से शुद्ध और ताजा प्लेन मावा। प्रामाणिक पारंपरिक खाना पकाने और मिठाइयों के लिए आदर्श। 1 किलो और 10 किलो पैकेजिंग में उपलब्ध है।',
            shrikhand: 'श्रीखंड',
            shrikhand_desc: 'केसर और इलायची के साथ स्वादिष्ट बनाया गया छना हुआ दही, एक प्रीमियम मिठाई।',
            chakka: 'चक्का / मस्कारा',
            chakka_desc: 'श्रीखंड और अन्य पारंपरिक मिठाइयाँ बनाने के लिए उपयोग किया जाने वाला गाढ़ा छना हुआ दही।',
            maska_full_cream: 'फुल क्रीम मस्का',
            maska_full_cream_desc: 'उच्च गुणवत्ता वाले फुल क्रीम दूध से बना समृद्ध और मलाईदार मस्का, पारंपरिक मिठाइयों के लिए आदर्श।',
            maska_low_fat: 'लो फैट मस्का',
            maska_low_fat_desc: 'हमारे पारंपरिक मस्का का एक हल्का संस्करण, कम वसा के साथ वही बेहतरीन बनावट प्रदान करता है।',
            paneer: 'ताज़ा पनीर',
            paneer_desc: 'शुद्ध दूध से बना नरम और मलाईदार पनीर, प्रोटीन और स्वाद से भरपूर।',
            butter: 'सफेद मक्खन (लोनी)',
            butter_desc: 'ताजा मथा हुआ पारंपरिक सफेद मक्खन, शुद्ध और प्राकृतिक स्वाद से भरपूर।',
            curd: 'ताज़ा दही',
            curd_desc: 'गाढ़ा, मलाईदार और प्राकृतिक रूप से किण्वित दही, प्रोबायोटिक्स से भरपूर।',
            ghee: 'देसी घी',
            ghee_desc: 'पारंपरिक रूप से तैयार किया गया शुद्ध घी, अपनी सुगंध और दानेदार बनावट के लिए प्रसिद्ध।',
            a2_ghee: 'A2 गाय का घी',
            a2_ghee_desc: 'पारंपरिक बिलोना पद्धति का उपयोग करके गिर गाय के दूध से बना प्रीमियम घी।',
            chaas: 'छाछ',
            chaas_desc: 'ताजगी देने वाली और हल्की पारंपरिक छाछ, हर भोजन के लिए एक प्राकृतिक शीतलक।',
            masala_chhas: 'मसाला छाछ',
            masala_chhas_desc: 'पारंपरिक भारतीय जड़ी-बूटियों और मसालों के मिश्रण के साथ मसालेदार छाछ, ताज़ा और पाचक।',
            sweets: 'पारंपरिक मिठाइयाँ',
            sweets_desc: 'प्रसाद डेयरी के शुद्ध अवयवों से बनी मावा, ड्राई फ्रूट और बंगाली मिठाइयों का उत्कृष्ट संग्रह।',
            lassi: 'मीठी लस्सी',
            lassi_desc: 'मलाईदार और ताज़ा दही आधारित पेय, एक स्मूथ बनावट के लिए पूरी तरह से मिश्रित।',
            sweets_general: 'दूध की मिठाइयाँ',
            sweets_general_desc: 'हमारे शुद्ध दूध और मावा से बनी पारंपरिक मिठाइयों का शानदार संग्रह।',
            packaging: 'उपलब्ध पैकेजिंग',
        },
        product_detail: {
            home: 'मुख्य पृष्ठ',
            products: 'उत्पाद',
            reviews: 'समीक्षाएं',
            add_to_cart: 'कार्ट में जोड़ें',
            sku: 'एसकेયુ',
            category: 'श्रेणी',
            tags: 'टैग',
            tags_value: 'जैविक, ताजा, डेयरी',
            desc_suffix: 'हमारी खुश गायों के 100% जैविक दूध से बनाया गया। पोषक तत्वों और प्रामाणिक स्वाद से भरपूर।',
            packaging: 'पैकेजिंग',
            storage: 'भंडारण',
            origin: 'उत्पत्ति',
            whatsapp_chat: 'व्हाट्सएप पर चैट करें',
            bulk_order_title: 'थोक ऑर्डर और अनुकूलन',
            bulk_order_desc: 'अनुरोध के अनुसार अनुकूलन उपलब्ध है। हम बड़े आयोजनों, शादियों, होटलों और विशिष्ट पैकेजिंग/ब्रांडिंग विकल्पों के लिए सेवा प्रदान करते हैं।',
            bulk_order_inquiry: 'थोक ऑर्डर के लिए पूछताछ करें',
        },
        about: {
            who_we_are: 'हम कौन हैं',
            title: 'हमारे बारे में',
            introductions: 'हमारा परिचय',
            heading: 'हम सबसे अच्छे डेयरी फार्म हैं',
            description: 'हम प्रकृति की शक्ति में विश्वास करते हैं। हमारी गायें हरे चरागाहों पर स्वतंत्र रूप से चरती हैं, जो पोषक तत्वों और स्वाद से भरपूर उच्चतम गुणवत्ता वाला दूध सुनिश्चित करती हैं।',
            years_exp: 'डेयरी उद्योग में वर्षों का अनुभव',
            natural_products: '100% प्राकृतिक उत्पाद',
            modern_tech: 'आधुनिक तकनीक',
            certified_organic: 'प्रमाणित जैविक',
            expert_farmers: 'विशेषज्ञ किसान',
            discover_more: 'और जानें',
        },
        team: {
            meet_farmers: 'किसानों से मिलें',
            title: 'हमारी टीम',
            founder: 'संस्थापक',
            head_idea: 'हेड ऑफ आइडिया',
            ceo: 'सीईओ',
            farmer: 'किसान',
            designer: 'डिजाइनर',
            marketer: 'मार्केटर',
        },
        contact: {
            get_touch: 'संपर्क करें',
            title: 'हमसे संपर्क करें',
            phone: 'फ़ोन नंबर',
            email: 'ईमेल पता',
            location: 'स्थान',
            opening_hours: 'खुलने का समय',
            send_message: 'संदेश भेजें',
            heading: 'हमें आपसे सुनना अच्छा लगता है',
            your_name: 'आपका नाम',
            your_email: 'आपका ईमेल',
            subject: 'विषय',
            message: 'संदेश',
            send_btn: 'संदेश भेजें',
            sent_success: 'संदेश भेजा गया!',
            sent_desc: 'हम जल्द से जल्द आपसे संपर्क करेंगे।',
        },
        footer: {
            about_us: 'हमारे बारे में',
            about_desc: 'प्रसाद डेयरी प्रोडक्ट्स हमारे फार्म से सीधे आपकी मेज पर शुद्ध, ताजा डेयरी लाने के लिए समर्पित है। हर बूंद में परंपरा गुणवत्ता से मिलती है।',
            products: 'उत्पाद',
            business_hours: 'व्यापार के घंटे',
            subscribe: 'हमें सब्सक्राइब करें',
            subscribe_desc: 'हमें सब्सक्राइब करें और सीधे अपने इनबॉक्स में हमारे अपडेट प्राप्त करें',
            email_placeholder: 'ईमेल पता',
            subscribe_btn: 'सब्सक्राइब',
            rights: '2025 प्रसाद डेयरी प्रोडक्ट्स। सर्वाधिकार सुरक्षित।',
            emergency: 'आपातकालीन सेवा',
            mon_fri: 'સોમ - શુક્ર',
            sat: 'શનિવાર',
            careers: 'करियर',
            faq: 'सामान्य प्रश्न',
            privacy: 'गोपनीयता नीति',
            terms: 'सेवा की शर्तें',
            shipping: 'शिपिंग जानकारी',
            returns: 'रिटर्न और रिफंड',
            },
            seo: {
            home_title: 'प्रसाद डेयरी प्रोडक्ट्स | शुद्ध देसी घी और गिर का ताजा दूध',
            home_desc: 'प्रसाद डेयरी की शुद्धता का अनुभव करें। हम गिर वन क्षेत्र के 58 गांवों से प्राप्त प्रामाणिक देसी घी, श्रीखंड, पनीर और ताजा दूध उत्पाद प्रदान करते हैं।',
            home_keywords: 'प्रसाद डेयरी, देसी घी गिर, ताजा दूध गुजरात, श्रीखंड तालाला, शुद्ध डेयरी उत्पाद भारत, जैविक घी, गिर गाय का घी',
            products_title: 'हमारे प्रीमियम डेयरी उत्पाद | प्रसाद डेयरी',
            products_desc: 'हमारे शुद्ध डेयरी उत्पादों की श्रेणी देखें: घी, मावा, श्रीखंड, बासुंदी और मलाई पनीर। पीढ़ियों के अनुभव और अटूट शुद्धता के साथ तैयार किया गया।',
            products_keywords: 'डेयरी उत्पादों की सूची, ऑनलाइन घी खरीदें, श्रीखंड फ्लेवर, शुद्ध मावा खोया, ताजा पनीर गुजरात',
            about_title: 'हमारी विरासत और मिशन | प्रसाद डेयरी के बारे में',
            about_desc: 'गिर में स्थापित, प्रसाद डेयरी को 20 से अधिक वर्षों का अनुभव है। हम मालधारी समुदाय को सशक्त बनाते हैं और गिर वर्षा वन क्षेत्र से ताजा दूध प्राप्त करते हैं।',
            about_keywords: 'प्रसाद डेयरी का इतिहास, गिर डेयरी फार्म, मालधारी समुदाय सहायता, टिकाऊ डेयरी खेती',
            team_title: 'हमारी समर्पित टीम से मिलें | प्रसाद डेयरी',
            team_desc: 'प्रसाद डेयरी के पीछे समर्पित किसानों और विशेषज्ञों से मिलें। हमारी टीम खेत से लेकर मेज तक उच्चतम गुणवत्ता मानकों को सुनिश्चित करती।',
            contact_title: 'हमसे संपर्क करें | प्रसाद डेयरी प्रोडक्ट्स',
            contact_desc: 'कोई प्रश्न हैं? थोक ऑर्डर या हमारे ताजा डेयरी उत्पादों के बारे में पूछताछ के लिए प्रसाद डेयरी से संपर्क करें।',
            }
            }
            };

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    // Load language from local storage on initial render
    useEffect(() => {
        const savedLanguage = localStorage.getItem('language');
        if (savedLanguage && translations[savedLanguage]) {
            setLanguage(savedLanguage);
        }
    }, []);

    // Save language to local storage whenever it changes
    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        const keys = key.split('.');
        let value = translations[language];
        for (const k of keys) {
            value = value?.[k];
        }
        return value || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);