import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
    en: {
        nav: {
            home: 'Home',
            products: 'Products',
            about: 'About',
            team: 'Team',
            contact: 'Contact',
        },
        slider: {
            slide1: {
                subtitle: 'Redefining Quality – Dairy Products from the Heart of Gir.',
                title: 'Raw Milk\'s Natural Resources from the Gir Rain Forest Area.',
                btn_primary: 'Our Products',
                btn_secondary: 'About Us'
            },
            slide2: {
                subtitle: 'Empowering the Maldhari Community.',
                title: 'Sourcing from 58 villages with 60 milk collection centers.',
                btn_primary: 'Shop Now',
                btn_secondary: 'Learn More'
            },
            slide3: {
                subtitle: "Blending Tradition with Modern Scale",
                title: 'Presently we have a 30,000 sq. feet factory layout with well-maintained equipment, backed by over 20 years of experience.',
                btn_primary: 'View Range',
                btn_secondary: 'Contact Us'
            }
        },
        home: {
            welcome: 'Welcome to our dairy farm',
            hero_title: 'PRASAD DAIRY',
            our_products: 'Our Products',
            about_us: 'About Us',
            know_about: 'Our History',
            know_about_sub: 'About Us',
            know_about_desc: 'Founded in Gir\'s capital, we have more than 20 years of experience. We started out in a 10x10 shed and have grown into a 30,000 sq. feet factory layout with well-maintained equipment. Our journey began by gathering milk from neighboring villages. Currently, our collection includes the entire Gir Forest Area and neighboring Talukas, covering 58 villages with 60 milk collection centers.',
            award: 'YOUNG FARM AWARD 2022',
            service_details: 'Service Details',
            read_more: 'Read More',
            services: 'Services',
            what_provide: 'WHAT WE PROVIDE',
            fresh_milk: 'Fresh Milk & Curd',
            dairy_products: 'Dairy Products',
            organic_product: 'Organic Product',
            stats_projects: 'Milk Collection Centers',
            stats_mates: 'Maldhari Families',
            stats_capture: 'Per Day Milk Collection (Liters)',
            stats_customers: 'Happy Customers',
            stats_satisfaction: 'Quality Satisfaction',
            testimonials_title: 'Our Testimonials',
            testimonials_heading: 'WHAT PEOPLE SAY',
            testimonials_quote: 'Farmers tend to be predominantly enterprising individuals, which means that they are usually quite natural leaders who thrive at influencing and persuading others.',
            featured_title: 'Featured',
            featured_heading: 'FEATURED PRODUCTS',
            more_products: 'More Products',
            farm_house: 'The Farm House',
            organic_100: '100% Organic',
            farm_fresh: '100% Pure',
            made_love: 'Made with Love',
            premium_quality: 'Premium Quality',
            team_title: 'Our Team',
            team_heading: 'EXPERT FARMER',
            why_choose: 'Why Choose Us',
            why_choose_heading: 'BEST DAIRY FARM',
        },
        products: {
            shop_now: 'Shop Now',
            title: 'OUR PRODUCTS',
            search_placeholder: 'Search products...',
            view_details: 'View Details',
            milk_solids: 'Milk Solids',
            desserts: 'Desserts',
            yogurt: 'Yogurt',
            cheese: 'Cheese',
            spreads: 'Spreads',
            khoa: 'Khoa',
            khoa_desc: 'Traditional milk solid',
            shrikhand: 'Shrikhand',
            shrikhand_desc: 'Sweet yogurt dessert',
            chakka: 'Chakka',
            chakka_desc: 'Strained yogurt base',
            paneer: 'M Paneer',
            paneer_desc: 'Fresh cottage cheese',
            butter: 'Butter',
            butter_desc: 'Churned fresh butter',
            curd: 'Curd',
            curd_desc: 'Fresh homemade curd',
            ghee: 'Pure Ghee',
            ghee_desc: 'Traditional clarified butter',
            sweets: 'Milk Sweets',
            sweets_desc: 'Assorted dairy sweets',
        },
        product_detail: {
            home: 'Home',
            products: 'Products',
            reviews: 'Reviews',
            add_to_cart: 'Add to Cart',
            sku: 'SKU',
            category: 'Category',
            tags: 'Tags',
            tags_value: 'Organic, Fresh, Dairy',
            desc_suffix: 'Made from 100% organic milk from our happy cows. Rich in nutrients and authentic taste.',
        },
        about: {
            who_we_are: 'Who We Are',
            title: 'ABOUT US',
            introductions: 'Our History',
            heading: 'Our History',
            description1: 'Founded in Gir\'s capital, we have more than 20 years of experience.Raw Milk\'s Natural Resources because of the Gir Rain Forest Area.',
            description2: 'We started out in a 10x10 shed. Presently we have a 30,000 sq. feet factory layout with well-maintained equipment.',
            description3: 'Our journey began by gathering milk from neighbouring villages.\n' +
                'Currently our collection includes the entire Gir Forest Area and neighbouring Talukas contain 58 villages with 60 milk collection centers. Last year, we achieved a daily milk collection capacity of over 20,000 liters, and we are still growing.',
            years_exp: 'Years of Experience in Dairy Industry',
            natural_products: '100% Natural Products',
            modern_tech: 'Modern Technology',
            certified_organic: 'Certified Organic',
            expert_farmers: 'Expert Farmers',
            discover_more: 'Discover More',
            v: {
                title: 'Our Vision',
                desc1: 'Our vision is to empower the Maldhari community by fostering sustainable practices and building a collaborative ecosystem, with the ambitious goal of collecting 1,82,50,000 liters of milk per annum.',
                desc2: 'Exploring high values for Quality and Standards with no compromise in Quality and Purity.'
            },
            cv:{
                title: 'Core Values',
                quality: 'Quality',
                quality_desc: 'Ensuring high standards in the production and processing of dairy products.',
                integrity: 'Integrity',
                integrity_desc: 'Conducting business with honesty and transparency, from sourcing to distribution.',
                innovation:'Innovation',
                innovation_desc: 'Embracing new technologies and methods to improve efficiency and product quality.',
                customer_focus:'Customer Focus',
                customer_focus_desc: 'Prioritizing customer satisfaction through consistent quality and service.',
                community_engagement:'Community Engagement',
                community_engagement_desc: 'Contributing positively to local communities, supporting farmers, and participating in community initiatives.',
                continuous_improvement:'Continuous Improvement',
                continuous_improvement_desc: 'Striving for ongoing improvement in processes, products, and sustain ability practices.'


            }
        },

        team: {
            meet_farmers: 'Meet the Farmers',
            title: 'OUR TEAM',
            founder: 'Founder',
            head_idea: 'Head of Idea',
            ceo: 'CEO',
            farmer: 'Farmer',
            designer: 'Designer',
            marketer: 'Marketer',
        },
        contact: {
            get_touch: 'Get in Touch',
            title: 'CONTACT US',
            phone: 'Phone Number',
            email: 'Email Address',
            location: 'Location',
            opening_hours: 'Opening Hours',
            send_message: 'Send Message',
            heading: 'WE LOVE TO HEAR FROM YOU',
            your_name: 'Your Name',
            your_email: 'Your Email',
            subject: 'Subject',
            message: 'Message',
            send_btn: 'Send Message',
            sent_success: 'Message Sent!',
            sent_desc: "We'll get back to you as soon as possible.",
        },
        footer: {
            about_us: 'About Us',
            about_desc: 'Prasad Dairy Products is dedicated to bringing the purest, freshest dairy from our farm directly to your table. Tradition meets quality in every drop.',
            products: 'Products',
            business_hours: 'Business Hours',
            quick_links: 'Quick Links',
            subscribe: 'Subscribe Us',
            subscribe_desc: 'Subscribe us & receive our office & update in your inbox directly',
            email_placeholder: 'Email address',
            subscribe_btn: 'Subscribe',
            rights: '2025 Prasad Dairy Products. All rights reserved.',
            emergency: 'Contact Number',
            mon_fri: 'Mon - Sat',
            sat: 'Sunday',
            careers: 'Careers',
            faq: 'FAQ',
            contact: 'Contact Us',
        }
    },
    gu: {
        nav: {
            home: 'મુખ્ય પૃષ્ઠ',
            products: 'ઉત્પાદનો',
            about: 'અમારા વિશે',
            team: 'ટીમ',
            contact: 'સંપર્ક',
        },
        slider: {
            slide1: {
                subtitle: 'અમારા ડેરી ફાર્મ પર આપનું સ્વાગત છે',
                title: 'પ્રસાદ ડેરી',
                btn_primary: 'અમારા ઉત્પાદનો',
                btn_secondary: 'અમારા વિશે'
            },
            slide2: {
                subtitle: 'શુદ્ધ અને સ્વસ્થ',
                title: 'દરરોજ તાજું દૂધ',
                btn_primary: 'હમણાં ખરીદો',
                btn_secondary: 'વધુ શીખો'
            },
            slide3: {
                subtitle: 'કુદરતનું શ્રેષ્ઠ',
                title: '100% ઓર્ગેનિક ઉત્પાદનો',
                btn_primary: 'શ્રેણી જુઓ',
                btn_secondary: 'અમારો સંપર્ક કરો'
            }
        },
        home: {
            welcome: 'અમારા ડેરી ફાર્મ પર આપનું સ્વાગત છે',
            hero_title: 'પ્રસાદ ડેરી',
            our_products: 'અમારા ઉત્પાદનો',
            about_us: 'અમારા વિશે',
            know_about: 'અમારા ફાર્મ અને ઇતિહાસ વિશે જાણો',
            know_about_sub: 'અમારા વિશે',
            know_about_desc: 'અમે વિશ્વાસ અને પ્રામાણિકતા સાથે 30 વર્ષથી વધુ સમયથી આ ઉદ્યોગમાં કાર્યરત છીએ. જો આપણે વૈશ્વિક પોષણ સુધારવા માટે અમારું લક્ષ્ય પ્રાપ્ત કરવું હોય તો બધાએ સાથે મળીને કામ કરવું પડશે.',
            award: 'યંગ ફાર્મ એવોર્ડ 2022',
            service_details: 'સેવા વિગતો',
            read_more: 'વધુ વાંચો',
            services: 'સેવાઓ',
            what_provide: 'અમે શું પ્રદાન કરીએ છીએ',
            fresh_milk: 'તાજું દૂધ અને દહીં',
            dairy_products: 'ડેરી ઉત્પાદનો',
            organic_product: 'ઓર્ગેનિક ઉત્પાદન',
            stats_projects: 'પ્રોજેક્ટ્સ પૂર્ણ',
            stats_mates: 'નિષ્ણાત સાથીઓ',
            stats_capture: 'વિશ્વવ્યાપી કેપ્ચર',
            stats_customers: 'ખુશ ગ્રાહકો',
            stats_satisfaction: 'સંતોષ',
            testimonials_title: 'અમારા પ્રશંસાપત્રો',
            testimonials_heading: 'લોકો શું કહે છે',
            testimonials_quote: 'ખેડૂતો મુખ્યત્વે સાહસિક વ્યક્તિઓ હોય છે, જેનો અર્થ એ છે કે તેઓ સામાન્ય રીતે કુદરતી નેતાઓ હોય છે જે અન્યને પ્રભાવિત કરવામાં અને સમજાવવામાં સફળ થાય છે.',
            featured_title: 'વિશિષ્ટ',
            featured_heading: 'વિશિષ્ટ ઉત્પાદનો',
            more_products: 'વધુ ઉત્પાદનો',
            farm_house: 'ફાર્મ હાઉસ',
            organic_100: '100% ઓર્ગેનિક',
            farm_fresh: 'ફાર્મ તાજું',
            made_love: 'પ્રેમથી બનાવેલ',
            premium_quality: 'પ્રીમિયમ ગુણવત્તા',
            team_title: 'અમારી ટીમ',
            team_heading: 'નિષ્ણાત ખેડૂત',
            news_title: 'સમાચાર ફીડ્સ',
            news_heading: 'બ્લોગ અને આંતરદૃષ્ટિ',
            more_news: 'વધુ સમાચાર',
        },
        products: {
            shop_now: 'હમણાં ખરીદો',
            title: 'અમારા ઉત્પાદનો',
            search_placeholder: 'ઉત્પાદનો શોધો...',
            view_details: 'વિગતો જુઓ',
            milk_solids: 'દૂધના ઘન પદાર્થો',
            desserts: 'મીઠાઈઓ',
            yogurt: 'દહીં',
            cheese: 'ચીઝ',
            spreads: 'સ્પ્રેડ્સ',
            khoa: 'માવો',
            khoa_desc: 'પરંપરાગત દૂધનો ઘન પદાર્થ',
            shrikhand: 'શ્રીખંડ',
            shrikhand_desc: 'મીઠી દહીંની મીઠાઈ',
            chakka: 'ચક્કા',
            chakka_desc: 'ગાળેલું દહીં',
            paneer: 'પનીર',
            paneer_desc: 'તાજું કોટેજ ચીઝ',
            butter: 'માખણ',
            butter_desc: 'તાજું માખણ',
            curd: 'દહીં',
            curd_desc: 'તાજું ઘરનું દહીં',
            ghee: 'શુદ્ધ ઘી',
            ghee_desc: 'પરંપરાગત સ્પષ્ટ માખણ',
            sweets: 'દૂધની મીઠાઈઓ',
            sweets_desc: 'વિવિધ દૂધની મીઠાઈઓ',
        },
        product_detail: {
            home: 'મુખ્ય પૃષ્ઠ',
            products: 'ઉત્પાદનો',
            reviews: 'સમીક્ષાઓ',
            add_to_cart: 'કાર્ટમાં ઉમેરો',
            sku: 'એસકેયુ',
            category: 'શ્રેણી',
            tags: 'ટૅગ્સ',
            tags_value: 'ઓર્ગેનિક, તાજું, ડેરી',
            desc_suffix: 'અમારી ખુશ ગાયોના 100% ઓર્ગેનિક દૂધમાંથી બનાવેલ. પોષક તત્વો અને અધિકૃત સ્વાદથી સમૃદ્ધ.',
        },
        about: {
            who_we_are: 'અમે કોણ છીએ',
            title: 'અમારા વિશે',
            introductions: 'અમારો પરિચય',
            heading: 'અમે શ્રેષ્ઠ ડેરી ફાર્મ છીએ',
            description: 'અમે કુદરતની શક્તિમાં માનીએ છીએ. અમારી ગાયો લીલા ઘાસના મેદાનોમાં મુક્તપણે ચરે છે, જે પોષક તત્વો અને સ્વાદથી ભરપૂર ઉચ્ચ ગુણવત્તાવાળું દૂધ સુનિશ્ચિત કરે છે.',
            years_exp: 'ડેરી ઉદ્યોગમાં વર્ષોનો અનુભવ',
            natural_products: '100% કુદરતી ઉત્પાદનો',
            modern_tech: 'આધુનિક ટેકનોલોજી',
            certified_organic: 'પ્રમાણિત ઓર્ગેનિક',
            expert_farmers: 'નિષ્ણાત ખેડૂતો',
            discover_more: 'વધુ શોધો',
        },
        team: {
            meet_farmers: 'ખેડૂતોને મળો',
            title: 'અમારી ટીમ',
            founder: 'સ્થાપક',
            head_idea: 'હેડ ઓફ આઈડિયા',
            ceo: 'સીઈઓ',
            farmer: 'ખેડૂત',
            designer: 'ડિઝાઈનર',
            marketer: 'માર્કેટર',
        },
        contact: {
            get_touch: 'સંપર્કમાં રહો',
            title: 'અમારો સંપર્ક કરો',
            phone: 'ફોન નંબર',
            email: 'ઇમેઇલ સરનામું',
            location: 'સ્થાન',
            opening_hours: 'ખુલવાનો સમય',
            send_message: 'સંદેશ મોકલો',
            heading: 'અમને તમારી પાસેથી સાંભળવું ગમશે',
            your_name: 'તમારું નામ',
            your_email: 'તમારું ઇમેઇલ',
            subject: 'વિષય',
            message: 'સંદેશ',
            send_btn: 'સંદેશ મોકલો',
            sent_success: 'સંદેશ મોકલ્યો!',
            sent_desc: 'અમે જલ્દીથી તમારો સંપર્ક કરીશું.',
        },
        footer: {
            about_us: 'અમારા વિશે',
            about_desc: 'પ્રસાદ ડેરી પ્રોડક્ટ્સ અમારા ફાર્મથી સીધા તમારા ટેબલ પર શુદ્ધ, તાજું દૂધ લાવવા માટે સમર્પિત છે. દરેક ટીપામાં પરંપરા ગુણવત્તાને મળે છે.',
            products: 'ઉત્પાદનો',
            business_hours: 'વ્યવસાયનો સમય',
            subscribe: 'અમને સબ્સ્ક્રાઇબ કરો',
            subscribe_desc: 'અમને સબ્સ્ક્રાઇબ કરો અને સીધા તમારા ઇનબોક્સમાં અમારા અપડેટ્સ મેળવો',
            email_placeholder: 'ઇમેઇલ સરનામું',
            subscribe_btn: 'સબ્સ્ક્રાઇબ',
            rights: '2025 પ્રસાદ ડેરી પ્રોડક્ટ્સ. સર્વાધિકાર સુરક્ષિત.',
            emergency: 'ઇમરજન્સી સેવા',
            mon_fri: 'સોમ - શુક્ર',
            sat: 'શનિવાર',
            careers: 'કારકિર્દી',
            faq: 'પ્રશ્નો',
        }
    },
    hi: {
        nav: {
            home: 'मुख्य पृष्ठ',
            products: 'उत्पाद',
            about: 'हमारे बारे में',
            team: 'टीम',
            contact: 'संपर्क',
        },
        slider: {
            slide1: {
                subtitle: 'हमारे डेयरी फार्म में आपका स्वागत है',
                title: 'प्रसाद डेयरी',
                btn_primary: 'हमारे उत्पाद',
                btn_secondary: 'हमारे बारे में'
            },
            slide2: {
                subtitle: 'शुद्ध और स्वस्थ',
                title: 'हर दिन ताजा दूध',
                btn_primary: 'अभी खरीदें',
                btn_secondary: 'और जानें'
            },
            slide3: {
                subtitle: 'प्रकृति का सर्वश्रेष्ठ',
                title: '100% जैविक उत्पाद',
                btn_primary: 'रेंज देखें',
                btn_secondary: 'संपर्क करें'
            }
        },
        home: {
            welcome: 'हमारे डेयरी फार्म में आपका स्वागत है',
            hero_title: 'प्रसाद डेयरी',
            our_products: 'हमारे उत्पाद',
            about_us: 'हमारे बारे में',
            know_about: 'हमारे फार्म और इतिहास के बारे में जानें',
            know_about_sub: 'हमारे बारे में',
            know_about_desc: 'हम 30 से अधिक वर्षों से विश्वास और ईमानदारी के साथ इस उद्योग में काम कर रहे हैं। यदि हमें वैश्विक पोषण में सुधार के अपने लक्ष्य को प्राप्त करना है तो सभी को मिलकर काम करना होगा।',
            award: 'यंग फार्म अवार्ड 2022',
            service_details: 'सेवा विवरण',
            read_more: 'और पढ़ें',
            services: 'सेवाएं',
            what_provide: 'हम क्या प्रदान करते हैं',
            fresh_milk: 'ताजा दूध और दही',
            dairy_products: 'डेयरी उत्पाद',
            organic_product: 'जैविक उत्पाद',
            stats_projects: 'परियोजनाएं पूर्ण',
            stats_mates: 'विशेषज्ञ साथी',
            stats_capture: 'विश्वव्यापी पहुंच',
            stats_customers: 'खुश ग्राहक',
            stats_satisfaction: 'संतुष्टि',
            testimonials_title: 'हमारे प्रशंसापत्र',
            testimonials_heading: 'लोग क्या कहते हैं',
            testimonials_quote: 'किसान मुख्य रूप से उद्यमी व्यक्ति होते हैं, जिसका अर्थ है कि वे आमतौर पर काफी स्वाभाविक नेता होते हैं जो दूसरों को प्रभावित करने और राजी करने में सफल होते हैं।',
            featured_title: 'विशेष',
            featured_heading: 'विशेष उत्पाद',
            more_products: 'अधिक उत्पाद',
            farm_house: 'फार्म हाउस',
            organic_100: '100% जैविक',
            farm_fresh: 'खेत का ताजा',
            made_love: 'प्यार से बनाया गया',
            premium_quality: 'प्रीमियम गुणवत्ता',
            team_title: 'हमारी टीम',
            team_heading: 'विशेषज्ञ किसान',
            news_title: 'समाचार फ़ीड',
            news_heading: 'ब्लॉग और अंतर्दृष्टि',
            more_news: 'अधिक समाचार',
        },
        products: {
            shop_now: 'अभी खरीदारी करें',
            title: 'हमारे उत्पाद',
            search_placeholder: 'उत्पाद खोजें...',
            view_details: 'विवरण देखें',
            milk_solids: 'दूध के ठोस पदार्थ',
            desserts: 'मिठाइयाँ',
            yogurt: 'दही',
            cheese: ' पनीर',
            spreads: 'स्प्रेड्स',
            khoa: 'खोया',
            khoa_desc: 'पारंपरिक दूध का ठोस पदार्थ',
            shrikhand: 'श्रीखंड',
            shrikhand_desc: 'मीठी दही मिठाई',
            chakka: 'चक्का',
            chakka_desc: 'छना हुआ दही',
            paneer: 'पनीर',
            paneer_desc: 'ताजा पनीर',
            butter: 'मक्खन',
            butter_desc: 'ताजा मक्खन',
            curd: 'दही',
            curd_desc: 'ताजा घर का बना दही',
            ghee: 'शुद्ध घी',
            ghee_desc: 'पारंपरिक स्पष्ट मक्खन',
            sweets: 'दूध की मिठाइयाँ',
            sweets_desc: 'विभिन्न डेयरी मिठाइयाँ',
        },
        product_detail: {
            home: 'मुख्य पृष्ठ',
            products: 'उत्पाद',
            reviews: 'समीक्षाएं',
            add_to_cart: 'कार्ट में जोड़ें',
            sku: 'एसकेયુ',
            category: 'श्रेणी',
            tags: 'टैग',
            tags_value: 'जैविक, ताजा, डेयरी',
            desc_suffix: 'हमारी खुश गायों के 100% जैविक दूध से बनाया गया। पोषक तत्वों और प्रामाणिक स्वाद से भरपूर।',
        },
        about: {
            who_we_are: 'हम कौन हैं',
            title: 'हमारे बारे में',
            introductions: 'हमारा परिचय',
            heading: 'हम सबसे अच्छे डेयरी फार्म हैं',
            description: 'हम प्रकृति की शक्ति में विश्वास करते हैं। हमारी गायें हरे चरागाहों पर स्वतंत्र रूप से चरती हैं, जो पोषक तत्वों और स्वाद से भरपूर उच्चतम गुणवत्ता वाला दूध सुनिश्चित करती हैं।',
            years_exp: 'डेयरी उद्योग में वर्षों का अनुभव',
            natural_products: '100% प्राकृतिक उत्पाद',
            modern_tech: 'आधुनिक तकनीक',
            certified_organic: 'प्रमाणित जैविक',
            expert_farmers: 'विशेषज्ञ किसान',
            discover_more: 'और जानें',
        },
        team: {
            meet_farmers: 'किसानों से मिलें',
            title: 'हमारी टीम',
            founder: 'संस्थापक',
            head_idea: 'हेड ऑफ आइडिया',
            ceo: 'सीईओ',
            farmer: 'किसान',
            designer: 'डिजाइनर',
            marketer: 'मार्केटर',
        },
        contact: {
            get_touch: 'संपर्क करें',
            title: 'हमसे संपर्क करें',
            phone: 'फ़ोन नंबर',
            email: 'ईमेल पता',
            location: 'स्थान',
            opening_hours: 'खुलने का समय',
            send_message: 'संदेश भेजें',
            heading: 'हमें आपसे सुनना अच्छा लगता है',
            your_name: 'आपका नाम',
            your_email: 'आपका ईमेल',
            subject: 'विषय',
            message: 'संदेश',
            send_btn: 'संदेश भेजें',
            sent_success: 'संदेश भेजा गया!',
            sent_desc: 'हम जल्द से जल्द आपसे संपर्क करेंगे।',
        },
        footer: {
            about_us: 'हमारे बारे में',
            about_desc: 'प्रसाद डेयरी प्रोडक्ट्स हमारे फार्म से सीधे आपकी मेज पर शुद्ध, ताजा डेयरी लाने के लिए समर्पित है। हर बूंद में परंपरा गुणवत्ता से मिलती है।',
            products: 'उत्पाद',
            business_hours: 'व्यापार के घंटे',
            subscribe: 'हमें सब्सक्राइब करें',
            subscribe_desc: 'हमें सब्सक्राइब करें और सीधे अपने इनबॉक्स में हमारे अपडेट प्राप्त करें',
            email_placeholder: 'ईमेल पता',
            subscribe_btn: 'सब्सक्राइब',
            rights: '2025 प्रसाद डेयरी प्रोडक्ट्स। सर्वाधिकार सुरक्षित।',
            emergency: 'आपातकालीन सेवा',
            mon_fri: 'सोम - शुक्र',
            sat: 'शनिवार',
            careers: 'करियर',
            faq: 'सामान्य प्रश्न',
        }
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    // Load language from local storage on initial render
    useEffect(() => {
        const savedLanguage = localStorage.getItem('language');
        if (savedLanguage && translations[savedLanguage]) {
            setLanguage(savedLanguage);
        }
    }, []);

    // Save language to local storage whenever it changes
    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        const keys = key.split('.');
        let value = translations[language];
        for (const k of keys) {
            value = value?.[k];
        }
        return value || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);